RCInvigilator/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RCInvigilator.Models;

namespace RCInvigilator.Controllers
{
	[Authorize]
    public class HomeController : Controller
    {
		private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            return RedirectToAction("Dashboard");
        }

        public ActionResult Dashboard()
        {
			ExamsController ec = new ExamsController();
            ViewBag.Message = "Adminstration Portal.";
			List<Exam> exams = db.Exams.ToList();
			string[] labels = new String[exams.Count];
			int[] inExams = new int[exams.Count];
			int[] authenticated = new int[exams.Count];
			for (var i = 0; i < labels.Length; ++i)
			{
				labels[i] = exams[i].CourseCode;
				inExams[i] = Exam.CountEnrolled(exams[i].ExamId);
				authenticated[i] = Exam.CountAuthenticated(exams[i].ExamId);
			}
			ViewBag.chartLabels = labels;
			ViewBag.inExams = inExams;
			ViewBag.authenticated = authenticated;
			
            return View(db.Sessions.ToList());
        }
    }
}

RCInvigilator/Controllers/SessionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RCInvigilator.Models;

namespace RCInvigilator.Controllers
{
	[Authorize]
    public class SessionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

		// GET: Sessions
		public ActionResult Index()
		{
			return RedirectToAction("Dashboard", "Home", null);
		}

        public ActionResult AddExam(int? id)
        {
            return RedirectToAction("CreateWithSession", "Exams", new { id = id });
        }

        public ActionResult AddInvigilator(int? id)
        {
            return RedirectToAction("CreateWithSession", "Invigilators", new { id = id });
        }

		public ActionResult ViewExams(int? id)
		{
			return RedirectToAction("Index", "Exams", new { sessionId = id });
		}

        // GET: Sessions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Session session = db.Sessions.Find(id);
			ViewData["Exams"] = db.Exams.Where(e => e.SessionId == id).ToList();
            if (session == null)
            {
                return HttpNotFound();
            }
            return View(session);
        }

        // GET: Sessions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sessions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SessionId,Campus,Building,Room,SessionDate")] Session session)
        {
            if (ModelState.IsValid)
            {
                db.Sessions.Add(session);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(session);
        }

        // GET: Sessions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Session session = db.Sessions.Find(id);
            if (session == null)
            {
                return HttpNotFound();
            }
            return View(session);
        }

        // POST: Sessions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SessionId,Campus,Building,Room,SessionDate")] Session session)
        {
            if (ModelState.IsValid)
            {
                db.Entry(session).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(session);
        }

        // GET: Sessions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Session session = db.Sessions.Find(id);
            if (session == null)
            {
                return HttpNotFound();
            }
            return View(session);
        }

        // POST: Sessions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Session session = db.Sessions.Find(id);
			List<Exam> exams = db.Exams.Where(e => e.SessionId == id).ToList();
			foreach (var e in exams)
			{
				List<ExamStudent> examStudents = db.ExamStudents.Where(es => es.ExamId == e.ExamId).ToList();
				foreach (var es in examStudents)
				{
					db.ExamStudents.Remove(es);
				}
				db.SaveChanges();
				db.Exams.Remove(e);
			}
			db.SaveChanges();
            db.Sessions.Remove(session);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RCInvigilator/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RCInvigilator/Views/Home/Dashboard.cshtml
@model IEnumerable<RCInvigilator.Models.Session>
@{
    ViewBag.Title = "Dashboard";
    string[] chartLabelsArray = ViewBag.chartLabels;
    int[] inExamsArray = ViewBag.inExams;
    int[] authenticatedArray = ViewBag.authenticated;
    string labels = "";
    string inExams = "";
    string authenticated = "";

    for (int i = 0; i < chartLabelsArray.Length; ++i)
    {
        if (i == 0)
        {
            labels += chartLabelsArray[i].ToString();
            inExams += inExamsArray[i].ToString();
            authenticated += authenticatedArray[i].ToString();
        }
        else
        {
            labels += "," + chartLabelsArray[i].ToString();
            inExams += "," + inExamsArray[i].ToString();
            authenticated += "," + authenticatedArray[i].ToString();         
        }
    }
    
}
@Scripts.Render("~/Scripts/Chart.min.js")

<div class="sessions-chart">
    <canvas id="myChart" style="width:100%; height:450px;"></canvas>
    <script type="text/javascript">
        var labels = "@labels";
        var labelsArray = labels.split(',');
        var inExams = "@inExams";
        var inExamsArray = inExams.split(',');
        var authenticated = "@authenticated";
        var authenticatedArray = authenticated.split(',');
        
    </script>
</div>

<section class="main-section">
    <!-- content goes here -->

    <div class="row">
        <div class="large-12 large-centered columns">
           

            @if (Model.Count() < 1)
            {
                <h3><a href="@Url.Action("Create", "Sessions")">There are no exam sessions yet. Click to create one!</a></h3>
            }
            else
            {
                <h3>Recent Sessions</h3>
                foreach (var session in Model)
                {
                    <div class="row collapse session-row">
                        <a href="@Url.Action("Details", "Sessions", new { id = session.SessionId })">
                            <div class="large-2 columns">
                                <h4>
                                    <small>Active</small><br>
                                    <div class="switch round">
                                        <input id="exampleCheckboxSwitch" type="checkbox" checked="checked">
                                        <label for="exampleCheckboxSwitch"></label>
                                    </div>
                                </h4>

                            </div>
                            <div class="large-3 columns">
                                <h4>
                                    <small>@Html.DisplayNameFor(model => model.Campus)</small><br>
                                    @Html.DisplayFor(modelItem => session.Campus)
                                </h4>
                            </div>
                            <div class="large-2 columns">
                                <h4>
                                    <small>@Html.DisplayNameFor(model => model.Building)</small><br>
                                    @Html.DisplayFor(modelItem => session.Building)
                                </h4>
                            </div>
                            <div class="large-2 columns">
                                <h4>
                                    <small>@Html.DisplayNameFor(model => model.Room)</small><br>
                                    @Html.DisplayFor(modelItem => session.Room)
                                </h4>
                            </div>
                            <div class="large-2 columns">
                                <h4>
                                    <small>@Html.DisplayNameFor(model => model.SessionDate)</small><br>
                                    @Html.DisplayFor(modelItem => session.SessionDate)
                                </h4>
                            </div>
                        </a>
                    </div>
                    <hr>
                }
            }
            
            <p><a href="@Url.Action("Create", "Sessions", null)" class="button right">Create Another Session</a></p>
        </div>
    </div>

</section>

RCInvigilator/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Login";
}

<div class="row">
    <div class="large-12 columns text-center" style="padding-top:150px;">
        <img src="~/Content/img/logo2.png" alt="logo" width="150" height="150">
        <h1 class="logo">RightExam</h1>
    </div>
</div>
<div class="row">
    <div class="large-8 large-centered columns">
        <p class="welcome">Welcome back!</p>
        <form>
            <div class="row">
                <div class="small-12 columns">
                    <input type="text" placeholder="Email">
                </div>
            </div>
            <div class="row">
                <div class="small-12 columns">
                    <input type="password" placeholder="Password">
                </div>
            </div>
            <div class="row">
                <div class="small-12 columns">
                    <a href="@Url.Action("Dashboard", "Home")" class="right secondary button">Sign In!</a>
                </div>
            </div>
        </form>
    </div>
</div>